name: Docker-acyion-demo
on: [push]
jobs:
  Ed-pull-to-dockerhub:
    runs-on: ubuntu-20.04
    steps:
    #---see "https://github.com/marketplace/actions/docker-setup-buildx"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      #----
      - name: Loging dockerhub 
        run: docker login -u ${{secrets.Docker_ID}} -p ${{secrets.Docker_PASSWORD}}
      - name: Build cross OS container with buildx
        run: >
          docker buildx build --platform linux/arm,linux/arm64,linux/amd64 
          -t ${{secrets.Docker_ID}}/my_nginx . --push
        # --push:Push to dockerhub

#---------------------------- Just build general image ----------------------------
      # - name: build-image
      #   run: docker build . --tag brotherhood86/my_nginx:latest
      # - name: Loging dockerhub and push
      #   run: docker login -u ${{secrets.Docker_ID}} -p ${{secrets.Docker_PASSWORD}}
      # - run: docker push ${{secrets.Docker_ID}}/my_nginx:latest
      # - name: run web
      #   run: docker run -p 80:80 -d brotherhood86/my_nginx:latest 
      #   #-p port maping, -d:run on background
       